### PR TITLE
just an attempt to help a bit.

### PR DESCRIPTION
**Pull request by NeonLightning**
hopefully this helps. i'm using it on my stream and i'm using it to try and clunkily understand the programming language

### CODE REVIEW

**Comment by NeonLightning** [comment]
still working at it got armor/weapon/accessory display working. had to chop out a chunk of php that was causing problems.

**Comment by NeonLightning** [comment]
If you don't mind i think i'm going to make this into my own program. i'll still credit. but aside from the memory reading i've basically rewritten most of the code. i'm not sure how you'd be able to merge at this point. and my goal is just ff7 at present.

**Comment by Dizzy611** [comment]
Oh wow. I haven't touched this project in a very long time, you've done an excellent job on this. Have at it! I wish your project the best of luck.

Just so you're aware, as far as attribution and licensing and such, under the MIT license you need to retain the content of the LICENSE file (including my attribution there) as long as you retain any of my code. You may relicense the resulting project as you wish if you want, but it should still have a section stating that portions of the work are under the MIT license and (C) Dylan Morrison.

Keep that in mind and you 100% have my blessing to do whatever you want with the project. I'm glad it inspired you!

Closing PR as it doesn't sound like we're merging :)

PS: I'll likely link to your project from the README.MD for this one telling people to look for yours if they want a continuation of this project, if you don't mind.

**Comment by NeonLightning** [comment]
I appreciate the kind words. I've no experience coding and you've been a godsend with your commenting and memory reading stuff.(I really need to get to doing that)

**Pull request closed without merging**
